name: benchapp
description: Simple Dart DB performance benchmark

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  objectboxdb:
    path: databases/objectboxdb
  isardb:
    path: databases/isardb
  hivedb:
    path: databases/hivedb
  core:
    path: databases/core
  args: ^2.3.0
