name: isardb
description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^2.1.0
  isar_flutter_libs: ^2.1.0
  path: ^1.8.0
  path_provider: ^2.0.8
  core:
    path: ../core
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  isar_generator: ^2.1.0
  build_runner: any


flutter:
  uses-material-design: true