name: objectboxdb

description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
#  firebase_core: ^1.12.0
#  cloud_firestore: ^3.1.7
  objectbox: ^1.4.0-dev.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.8
  sqflite: ^2.0.2
  path: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: any
  objectbox_generator: ^1.4.0-dev.0


flutter:
  uses-material-design: true